exports.roles = {
    ADMIN: 'ADMIN',
    STUDENT: 'STUDENT',
    CLASS_MONITOR: 'CLASS_MONITOR',
    HOMEROM_TEACHER: 'HOMEROM_TEACHER',
    LECTURER: 'LECTURER'
}

exports.statusUser = {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
}